trigger:
    resource: "@TriggerBundle/Controller/"
    type:     annotation
    prefix:   /

pipeline:
    resource: "@PipelineBundle/Controller/"
    type:     annotation
    prefix:   /tracker/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
